# Generated by Django 3.2.11 on 2022-01-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_auto_20220126_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfiles',
            name='college_name',
        ),
    ]
