# Generated by Django 3.2.11 on 2022-02-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_myuploadfiles_college_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfiles',
            name='college_name',
        ),
    ]
