# Generated by Django 3.2.11 on 2022-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_myuploadfiles_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfiles',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='summary'),
        ),
    ]
